# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactNativeEventBridgeSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReactNativeEventBridgeSwift
  pod 'Yoga', :path => './ReactNativeEventBridgeSwift/ReactNative/node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
  pod 'React', path: './ReactNativeEventBridgeSwift/ReactNative/node_modules/react-native', :subspecs => [
    'Core',
    'RCTImage',
    'RCTNetwork',
    'RCTText',
    'RCTWebSocket',
    'RCTAnimation',
  ]
  pod 'MSREventBridge', :path => './ReactNativeEventBridgeSwift/ReactNative/node_modules/react-native-event-bridge/MSREventBridge.podspec'
end
